import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle, ChevronDown, ChevronRight, Clock3, Filter, Home, Leaf, Menu, MessageCircle, Minus, RotateCcw, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Truck, X } from 'lucide-react';
import './tienda.css';

const API = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3001';
const ASSETS = '/store-assets/diez-rios';
const money = n => `$${Math.round(Number(n) || 0).toLocaleString('es-CL')}`;
const norm = s => String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const slugify = s => norm(s).replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const title = s => {
  const clean=String(s || '').replace(/^[^\p{L}\p{N}]+/u, '').trim();
  const uniform={
    'huevos de campo tamano l cafe':'Huevos de Campo Café Tamaño L – Bandeja 30 Unidades',
    '30 huevos jumbo':'Huevos de Campo Tamaño Jumbo – Bandeja 30 Unidades',
    'huevos especial (20un)':'Huevos de Campo Tamaño Especial – Bandeja 20 Unidades',
  };
  return uniform[norm(clean)]||clean;
};
const request = async (path, options) => { const r = await fetch(`${API}${path}`, options); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'No pudimos completar la solicitud'); return d; };
const localImages = { 1:'huevos-bandeja.png',2:'huevos-bandeja.png',3:'huevos-bandeja.png',4:'huevos-bandeja.png',5:'huevos-bandeja-xl.png',6:'caja-m.png',7:'caja-l.png',8:'caja-xl.png',9:'caja-jumbo.png',11:'queso-cabra.png',12:'aceitunas-verdes.jpg',13:'aceitunas-negras.jpg',14:'aceitunas-moradas.jpg',15:'promo-60-xl.jpg',16:'pack-campo.png',18:'promo-m.jpg',21:'aceitunas-rajadas.jpg' };
const category = p => { const s = norm(`${p?.category} ${p?.title}`); return s.includes('queso')?'Quesos':s.includes('aceituna')?'Aceitunas':(s.includes('promo')||s.includes('pack'))?'Promociones':'Huevos'; };
const fallback = { Huevos:'huevos-bandeja.png',Quesos:'queso-cabra.png',Aceitunas:'aceitunas-verdes.jpg',Promociones:'promo-60-xl.jpg' };
const summary = p => String(p?.description||'').replace(/\s+/g,' ').replace(/✔️.*$/u,'').trim();
const unitsFor = p => { if(p?.pack_units)return Number(p.pack_units);const standard=String(p?.title||'').match(/bandeja de (\d+)/i);if(standard)return Number(standard[1]);const match=String(p?.title||'').match(/(\d+)\s*(?:huevos|unidades|un\b)/i); return match?Number(match[1]):null; };
const eggColor = p => { const name=norm(p?.title); return name.includes('blanco')?'blancos':name.includes('cafe')?'cafe':'mixtos'; };
const eggTone = p => ({blancos:'Huevos blancos',cafe:'Huevos cafés',mixtos:'Huevos mixtos'})[eggColor(p)];
const eggCaliber = p => {
  const name=norm(p?.title);
  if(name.includes('especial'))return{name:'Especial',weight:'Más de 68 g'};
  if(name.includes('jumbo'))return{name:'Jumbo',weight:'Más de 74 g'};
  if(name.includes('xl'))return{name:'XL',weight:'63–70 g'};
  if(/(?:tamano|huevos) l\b/.test(name))return{name:'L',weight:'56–63 g'};
  return{name:'M',weight:'Más de 47 y hasta 54 g'};
};
const eggImage = p => {
  const name=norm(p?.title), units=unitsFor(p), bulk=Number(units)>=100;
  const tone=name.includes('blanco')?'blancos':name.includes('cafe')?'cafe':'mixtos';
  if(name.includes('xl'))return bulk?'caja-logo-huevos-xl-v6.jpg':`huevos-xl-${units===20?20:30}-hogar-v5.jpg`;
  if(bulk)return`caja-logo-huevos-${tone}-v6.jpg`;
  if(units===20)return`huevos-${tone}-20-hogar-v4.jpg`;
  if(tone==='cafe')return'huevos-cafe-30-hogar-v4.jpg';
  return`huevos-${tone}-hogar-v3.jpg`;
};
const imageFor = (p, local) => local ? `${ASSETS}/${category(p)==='Huevos'?eggImage(p):(localImages[p.id] || fallback[category(p)])}` : p.image_url;

// Display preview only; checkout always verifies the customer's actual price on the server.
function trayTotal(item) {
  const name=String(item.title||item.name||item.product_name||'').toLowerCase(),q=Number(item.quantity),price=Number(item.price);
  if(/\bm\b/.test(name)||!/huevo/.test(name)||/queso|aceituna|combo|pack|promo|empresa|caja|granel|\b(?:60|100|180)\b/.test(name)||!Number.isSafeInteger(q)||q<1||price<1000)return price*q;
  return Math.floor(q/3)*Math.round(price*2.5/100)*100+(q%3===2?Math.round(price*11/6/100)*100:(q%3)*price);
}
const previewLines = (lines, tiers) => {
  const result=lines.map(i=>({...i}));
  if(!tiers)return result;
  for(const i of result){const total=trayTotal(i);if(total<i.price*i.quantity)i.price=total/i.quantity;}
  const selected=result.filter(i=>{const t=String(i.title||'').toLowerCase(), sizes=t.match(/\b(?:20|30|60|100|180)\b/g)||[];i.units=sizes.length===1&&tiers[Number(sizes[0])]?Number(sizes[0]):0;return !/^huevos (m|l|xl|jumbo) (blancos|mixtos|cafés) · bandeja de/.test(t)&&/\bxl\b/.test(t)&&/huevo|bandeja|caja|promo/.test(t)&&!/queso|aceituna|combo|especial|empresa/.test(t)&&i.units;});
  const units=selected.reduce((s,i)=>s+i.units*i.quantity,0),current=selected.reduce((s,i)=>s+i.price*i.quantity,0);
  if(!Number.isSafeInteger(units)||units<1||units>180000)return result;
  const dp=Array(units+1).fill(Infinity);dp[0]=0;
  for(let n=1;n<=units;n++)for(const [pack,price] of Object.entries(tiers))if(n>=Number(pack))dp[n]=Math.min(dp[n],dp[n-Number(pack)]+price);
  const target=dp[units];if(!Number.isFinite(target)||target>=current)return result;
  let allocated=0;selected.forEach((i,index)=>{const amount=index===selected.length-1?target-allocated:Math.round(target*i.price*i.quantity/current);allocated+=amount;i.price=amount/i.quantity;});return result;
};
const previewPrice = (p,tiers,quantity=1) => previewLines([{...p,quantity,price:Number(p.price)}],tiers)[0].price*quantity;

function routeFrom(base) { const tail = base && location.pathname.startsWith(base) ? location.pathname.slice(base.length) : location.pathname; const a = tail.split('/').filter(Boolean); if (a[0]==='productos'&&a[1]) return {page:'product',id:Number(a[1].split('-')[0])}; if(a[0]==='productos')return{page:'catalog'}; if(a[0]==='colecciones')return{page:'catalog',cat:a[1]}; if(a[0]==='como-comprar')return{page:'how'}; if(a[0]==='nuestra-historia')return{page:'story'}; return{page:'home'}; }
function EggWeightGuide({expanded=false}){return <section className="dr-weight-guide"><h2>Los clasificamos por peso, no por apariencia</h2><p>La norma chilena NCh1376.Of78 clasifica los huevos por su peso con cáscara. En Diez Ríos elevamos en 2 g los extremos de referencia para nuestra selección comercial L y XL: L de 56 a 63 g y XL de 63 a 70 g. Su forma puede variar: dos huevos que se ven distintos pueden pertenecer a la misma categoría.</p><details open={expanded||undefined}><summary>¿Cómo clasificamos nuestros huevos?</summary><p><b>Nuestra selección:</b> L de 56 a 63 g · XL de 63 a 70 g. Estos son nuestros rangos comerciales; la tabla siguiente muestra la clasificación de la norma chilena.</p><table><caption>Referencia de clasificación por peso: NCh1376.Of78</caption><thead><tr><th scope="col">Categoría de peso</th><th scope="col">Peso por huevo</th></tr></thead><tbody>{[['Muy chico','Hasta 40 g'],['Chico','Más de 40 y hasta 47 g'],['Mediano (M)','Más de 47 y hasta 54 g'],['Grande (L)','Más de 54 y hasta 61 g'],['Extra grande (XL)','Más de 61 y hasta 68 g'],['Especial','Más de 68 g']].map(([name,weight])=><tr key={name}><th scope="row">{name}</th><td>{weight}</td></tr>)}</tbody></table><p><b>Jumbo en Diez Ríos:</b> nombre comercial de nuestra selección sobre 74 g, dentro de la categoría Especial. No es una categoría independiente de esta norma.</p><p><a href="https://www.chilehuevos.cl/storage/libraries/7,-Gu%C3%ADa%20Peso%20Huevos..pdf" target="_blank" rel="noopener noreferrer">Ver referencia de Chilehuevos (NCh1376.Of78)</a></p><p>La cantidad de huevos de cada bandeja se indica por separado. El color de la cáscara no define la categoría de peso.</p></details></section>}
function Qty({n,minus,plus}){return <div className="dr-qty"><button onClick={minus}><Minus/></button><b>{n}</b><button onClick={plus}>+</button></div>}
function Pic({p,local,className=''}){const [bad,setBad]=useState(false);return bad?<div className={`dr-fallback ${className}`}><Leaf/></div>:<img className={className} src={imageFor(p,local)} alt={title(p.title)} loading="lazy" onError={()=>setBad(true)}/>}
function Card({p,local,open,add,tiers}){const group=category(p),eggs=group==='Huevos',units=eggs&&unitsFor(p),caliber=eggs&&eggCaliber(p),soldOut=Number(p.stock)<=0,description=summary(p);if(eggs)return <article className="dr-card dr-card-huevos"><button className="dr-card-pic" onClick={()=>open(p)} aria-label={`Ver ${title(p.title)}`}><Pic p={p} local={local}/>{units&&<b className="dr-card-units">{units} huevos</b>}{soldOut&&<span>Agotado</span>}</button><div className="dr-egg-body"><button className="dr-card-title" onClick={()=>open(p)}>{title(p.title).replace(/\s*·\s*Bandeja de \d+$/i,'')}</button>{units&&<p className="dr-egg-pack">Bandeja de {units} unidades</p>}<p className="dr-egg-weight">Peso por huevo: {caliber.weight}</p><strong>{money(previewPrice(p,tiers))}</strong><button className="dr-card-add" disabled={soldOut} onClick={()=>add(p)}><ShoppingBag/><span className="dr-add-full">{soldOut?'Sin stock':'Agregar al carrito'}</span><span className="dr-add-short">{soldOut?'Sin stock':'Agregar'}</span></button></div></article>;return <article className={`dr-card dr-card-${slugify(group)}`}><button className="dr-card-pic" onClick={()=>open(p)}><Pic p={p} local={local}/>{eggs&&<i>{eggTone(p)}</i>}{units&&<b className="dr-card-units">{units} UN.</b>}{eggs&&<b className="dr-card-weight">{caliber.name} · {caliber.weight}</b>}{soldOut&&<span>Agotado</span>}</button>{eggs?<div className="dr-card-caliber"><b>{caliber.name}</b><span>{caliber.weight} por huevo</span></div>:<small>{group}</small>}<button className="dr-card-title" onClick={()=>open(p)}>{title(p.title)}</button>{group==='Quesos'&&description&&<p className="dr-card-description">{description}</p>}<strong>{money(previewPrice(p,tiers))}</strong>{previewPrice(p,tiers)<Number(p.price)&&<small>Precio por cantidad</small>}<button className="dr-card-add" disabled={soldOut} onClick={()=>add(p)}><ShoppingBag/><span className="dr-add-full">{soldOut?'Sin stock':'Agregar al carrito'}</span><span className="dr-add-short">{soldOut?'Sin stock':'Agregar'}</span></button></article>}

export default function Tienda({slug}){
  const local=slug.startsWith('diez-rios'), custom=['diezrios.com','www.diezrios.com'].includes(location.hostname), base=custom?'':`/tienda/${slug}`;
  const storageKey=`dr-store:${slug}`;
  const shellRef=useRef(null);
  const [route,setRoute]=useState(()=>routeFrom(base)),[store,setStore]=useState(null),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[menu,setMenu]=useState(false),[searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(''),[sort,setSort]=useState('featured'),[colorFilter,setColorFilter]=useState('all'),[filters,setFilters]=useState(false),[faq,setFaq]=useState(-1),[qty,setQty]=useState(1),[checkout,setCheckout]=useState(false),[success,setSuccess]=useState(null),[submitting,setSubmitting]=useState(false),[form,setForm]=useState({name:'',phone:'',address:'',city:'La Serena'}),[formError,setFormError]=useState(''),[lastOrder,setLastOrder]=useState(null),[hydrated,setHydrated]=useState(false);
  useEffect(()=>{const pop=()=>setRoute(routeFrom(base));addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[base]);
  useEffect(()=>{Promise.all([request(`/store/${slug}/info`),request(`/store/${slug}/products`)]).then(([s,p])=>{setStore(s);setProducts((p.products||[]).filter(x=>x.active!==false&&x.is_business!==true&&!(local&&category(x)==='Quesos'&&norm(x.title).includes('vaca'))))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[slug,local]);
  useEffect(()=>{if(!local)return;const previousTitle=document.title;document.title='Diez Ríos · Del campo a tu mesa';const head=document.head;const nodes=[['link',{rel:'manifest',href:'/diez-rios.webmanifest'}],['meta',{name:'theme-color',content:'#173b2b'}],['meta',{name:'apple-mobile-web-app-capable',content:'yes'}],['meta',{name:'apple-mobile-web-app-status-bar-style',content:'black-translucent'}],['link',{rel:'apple-touch-icon',href:`${ASSETS}/icono-diez-rios-oficial-v1.png`}]];const added=nodes.map(([tag,attrs])=>{const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));el.dataset.diezRios='true';head.appendChild(el);return el});return()=>{document.title=previousTitle;added.forEach(el=>el.remove())}},[local]);
  useEffect(()=>{if(!products.length||hydrated)return;try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');if(saved.customer)setForm(f=>({...f,...saved.customer}));if(saved.lastOrder)setLastOrder(saved.lastOrder);if(Array.isArray(saved.cart)){const restored=saved.cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?{p,q:Math.max(1,Number(i.q)||1)}:null}).filter(Boolean);setCart(restored)}}catch{}setHydrated(true)},[products,storageKey,hydrated]);
  useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(storageKey,JSON.stringify({customer:form,cart:cart.map(i=>({id:i.p.id,q:i.q})),lastOrder}))}catch{}},[storageKey,form,cart,lastOrder,hydrated]);
  const [upsell,setUpsell]=useState(null);
  const [quote,setQuote]=useState(null),[quoteError,setQuoteError]=useState('');
  const quoteKey=JSON.stringify({phone:form.phone,items:cart.map(i=>({productId:i.p.id,quantity:i.q}))});
  useEffect(()=>{
    if(!cart.length)return;
    let active=true; setQuote(null); setQuoteError('');
    if(!/^\d{8,15}$/.test(form.phone.replace(/\D/g,'')))return;
    const timer=setTimeout(()=>request(`/store/${slug}/quote`,{method:'POST',headers:{'Content-Type':'application/json'},body:quoteKey})
      .then(data=>{if(active)setQuote({...data,key:quoteKey})})
      .catch(()=>{if(active)setQuoteError('No pudimos verificar el precio. Revisa tu teléfono o intenta nuevamente.')}),350);
    return()=>{active=false;clearTimeout(timer)};
  },[checkout,quoteKey,slug]);
  const currentQuote=quote?.key===quoteKey?quote:null;
  const displayedLines=currentQuote?.items??previewLines(cart.map(i=>({...i.p,quantity:i.q,price:Number(i.p.price)})),store?.xlWelcomeTiers);
  const linePrice=id=>displayedLines.find(i=>Number(i.id)===Number(id))?.price??0;

  const go=useCallback((path,r)=>{history.pushState({},'',`${base}${path}`||'/');setRoute(r);setMenu(false);setSearchOpen(false);setCheckout(false);shellRef.current?.scrollTo({top:0,behavior:'smooth'})},[base]);
  const cats=useMemo(()=>['Huevos','Quesos','Aceitunas','Promociones'].filter(c=>products.some(p=>category(p)===c)),[products]);
  const shown=useMemo(()=>{let a=[...products];if(route.cat)a=a.filter(p=>slugify(category(p))===route.cat);if(colorFilter!=='all')a=a.filter(p=>category(p)==='Huevos'&&eggColor(p)===colorFilter);if(search)a=a.filter(p=>norm(p.title).includes(norm(search)));if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='name')a.sort((x,y)=>title(x.title).localeCompare(title(y.title),'es'));return a},[products,route.cat,colorFilter,search,sort]);
  const selected=products.find(p=>p.id===route.id)||products.find(p=>p.replaces_ids?.includes(route.id)),free=Number(store?.freeShipping??10000),wa=String(store?.whatsappPhone||'56942876413').replace(/\D/g,''),count=cart.reduce((s,i)=>s+i.q,0),total=currentQuote?.total??displayedLines.reduce((s,i)=>s+i.quantity*Number(i.price),0);
  const recommendations=useMemo(()=>{const purchased=new Set(success?.purchasedCategories||[]);if(!purchased.size)return[];return products.filter(p=>Number(p.stock)>0&&!purchased.has(category(p))).sort((a,b)=>{const rank={Quesos:0,Aceitunas:1,Promociones:2,Huevos:3};return(rank[category(a)]??9)-(rank[category(b)]??9)}).slice(0,3)},[products,success]);
  const add=useCallback((p,n=1)=>{if(Number(p.stock)<=0)return;setCart(a=>{const e=a.find(i=>i.p.id===p.id);return e?a.map(i=>i.p.id===p.id?{...i,q:i.q+n}:i):[...a,{p,q:n}]});setCartOpen(true);const after=(cart.find(i=>i.p.id===p.id)?.q||0)+n;if(after<=2&&previewPrice(p,store?.xlWelcomeTiers,after+1)<previewPrice(p,store?.xlWelcomeTiers,after)+Number(p.price)&&Number(p.stock)>=after+1)setUpsell({...p,offerQuantity:after+1})},[cart,store]);
  const change=(id,d)=>setCart(a=>a.map(i=>i.p.id===id?{...i,q:i.q+d}:i).filter(i=>i.q>0));
  const repeatLastOrder=()=>{const restored=(lastOrder?.items||[]).map(i=>{const p=products.find(x=>x.id===i.id&&Number(x.stock)>0);return p?{p,q:Math.max(1,Number(i.q)||1)}:null}).filter(Boolean);if(restored.length){setCart(restored);setCartOpen(true)}};
  const catalog=c=>{if(c&&c!=='Huevos')setColorFilter('all');return c?go(`/colecciones/${slugify(c)}`,{page:'catalog',cat:slugify(c)}):go('/productos',{page:'catalog'})};
  const open=p=>go(`/productos/${p.id}-${slugify(title(p.title))}`,{page:'product',id:p.id});
  const submit=async e=>{e.preventDefault();if(!currentQuote){setFormError('Espera la verificación del precio antes de confirmar.');return;}if(!form.name.trim()||form.phone.replace(/\D/g,'').length<8||!form.address.trim()){setFormError('Completa nombre, WhatsApp y dirección.');return}setSubmitting(true);try{const ordered={items:cart.map(i=>({id:i.p.id,q:i.q})),total,date:new Date().toISOString()},purchasedCategories=[...new Set(cart.map(i=>category(i.p)))];const d=await request(`/store/${slug}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,expectedTotal:currentQuote.total,items:cart.map(i=>({productId:i.p.id,quantity:i.q}))})});setLastOrder(ordered);setSuccess({...d,purchasedCategories});setCart([]);setCheckout(false)}catch(x){setFormError(x.message)}finally{setSubmitting(false)}};
  if(loading)return <div className="dr-state"><i/><p>Preparando productos frescos…</p></div>;if(error)return <div className="dr-state"><Leaf/><h1>Tienda temporalmente no disponible</h1><p>{error}</p><button onClick={()=>location.reload()}>Intentar nuevamente</button></div>;
  const header=<><div className="dr-ann"><Truck/>Delivery gratis por compras sobre {money(free)}</div><header className="dr-header"><button className="dr-menu-trigger" onClick={()=>setMenu(true)}><Menu/></button><button className="dr-logo" onClick={()=>go('',{page:'home'})}><b>DIEZ RÍOS</b><span>CAMPO · FAMILIA · ORIGEN</span></button><nav><div><button>Productos <ChevronDown/></button><aside>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}<button onClick={()=>catalog()}>Ver todos</button></aside></div><button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></nav><section><button onClick={()=>setSearchOpen(!searchOpen)}><Search/></button><button className="dr-bag" onClick={()=>setCartOpen(true)}><ShoppingBag/>{count>0&&<i>{count}</i>}</button></section></header><div className="dr-mobile-top"><button className="dr-mobile-brand" onClick={()=>go('',{page:'home'})}><b>DIEZ RÍOS</b><span>CAMPO · FAMILIA · ORIGEN</span></button><button className="dr-mobile-search" onClick={()=>setSearchOpen(!searchOpen)}><Search/><span>Buscar</span></button></div>{searchOpen&&<div className="dr-search"><Search/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos…"/><button onClick={()=>setSearch('')}><X/></button></div>}{menu&&<div className="dr-mobile"><div><b>MENÚ</b><button onClick={()=>setMenu(false)}><X/></button></div><button onClick={()=>go('',{page:'home'})}>Inicio</button><button onClick={()=>catalog()}>Todos los productos</button>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}<button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></div>}</>;
  const footer=<footer className="dr-footer"><section><div><small>COMPRA DIRECTO AL CAMPO</small><h2>Productos honestos,<br/>directo a tu mesa.</h2></div><a href={`https://wa.me/${wa}`} target="_blank" rel="noopener noreferrer"><MessageCircle/><span>Comprar por WhatsApp<br/><small>{wa === '56942876413' ? '+56 9 4287 6413' : `+${wa}`}</small></span></a></section><div className="dr-footer-grid"><div><b>DIEZ RÍOS</b><p>Alimentos de origen, seleccionados con dedicación y entregados directamente en tu hogar.</p></div><div><strong>Comprar</strong>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}</div><div><strong>Información</strong><button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></div><div><strong>Despachos</strong><p>La Serena y Coquimbo<br/>Lunes a sábado<br/>Pedidos antes de las 13:00</p></div></div><small>© {new Date().getFullYear()} Diez Ríos · Compra segura</small></footer>;
  return <div ref={shellRef} className={`dr-shell${cartOpen||menu||checkout?' dr-scroll-locked':''}`}>{header}
    {lastOrder&&<section className="dr-returning"><div><small>COMPRA RÁPIDA</small><b>{form.name?`¡Qué bueno verte de nuevo, ${form.name.trim().split(' ')[0]}!`:'¡Qué bueno verte de nuevo!'}</b><span>Tu último pedido y tus datos de entrega están guardados en este dispositivo.</span></div><button onClick={repeatLastOrder}><RotateCcw/>Repetir último pedido</button></section>}
    {route.page==='home'&&<main><section className="dr-hero"><div className="dr-hero-copy"><div className="dr-pills"><span>{store?.xlWelcomeTiers ? 'AHORRA POR CANTIDAD EN HUEVOS' : '5% OFF POR 2 BANDEJAS'}</span><span>DESPACHO GRATIS SOBRE {money(free)}</span></div><small>ALIMENTOS CON ORIGEN</small><h1>Del campo<br/>a tu mesa.</h1><p>Huevos de gallinas libres, quesos artesanales y aceitunas seleccionadas. Productos frescos, sin intermediarios y con entrega directa en La Serena y Coquimbo.</p><ul><li><CheckCircle/>Producción y selección responsable</li><li><CheckCircle/>Entrega directa, sin intermediarios</li><li><CheckCircle/>Atención cercana por WhatsApp</li></ul><button onClick={()=>catalog()}>Ver productos <ChevronRight/></button><em>★★★★★ &nbsp; Preferidos por familias de la región</em></div><div className="dr-hero-img"><img src={`${ASSETS}/hero.png`} alt="Productos Diez Ríos"/><span><Leaf/><b>100%</b>origen local</span></div></section>
    <section className="dr-values"><small>NUESTRA FORMA DE HACER LAS COSAS</small><h2>Dedicación en cada producto</h2><p>Creemos en los alimentos simples, honestos y bien hechos. Por eso cuidamos cada paso, desde el origen hasta tu puerta.</p><div><article><b>100%</b><strong>Gallinas libres</strong><span>Huevos de campo seleccionados con cuidado.</span></article><article><b>0</b><strong>Intermediarios</strong><span>Del productor directamente a tu hogar.</span></article><article><b>52</b><strong>Semanas al año</strong><span>Una relación constante con nuestros clientes.</span></article></div></section>
    <section className="dr-featured"><div className="dr-heading"><div><small>NUESTROS PRODUCTOS</small><h2>Delicias del campo</h2></div><button onClick={()=>catalog()}>Ver todo <ChevronRight/></button></div><div className="dr-categories">{[['Huevos','huevos-bandeja.png','Frescos, de gallinas libres'],['Quesos','queso-cabra.png','Queso de cabra fresco y artesanal'],['Aceitunas','aceitunas-verdes.jpg','Seleccionadas en su mejor punto']].map(([c,img,t])=><button key={c} onClick={()=>catalog(c)}><img src={`${ASSETS}/${img}`} alt={c}/><span><small>{t}</small><b>{c}</b><em>Comprar ahora →</em></span></button>)}</div></section>
    <section className="dr-how-preview"><small>ASÍ DE SIMPLE</small><h2>Cómo funciona</h2><div>{[['01','Elige','Agrega tus productos favoritos.'],['02','Confirma','Ingresa tus datos y dirección.'],['03','Coordinamos','Te contactamos por WhatsApp.'],['04','Recibe','Llevamos el campo a tu puerta.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><button onClick={()=>go('/como-comprar',{page:'how'})}>Ver entregas y condiciones <ChevronRight/></button></section></main>}
    {route.page==='catalog'&&<main className={`dr-catalog dr-catalog-${route.cat||'todos'}`}><section className="dr-banner"><small>CATÁLOGO DIEZ RÍOS</small><h1>{route.cat?cats.find(c=>slugify(c)===route.cat):'Todos los productos'}</h1><p>{route.cat==='quesos'?'Queso fresco de cabra, elaborado artesanalmente y entregado directo a tu hogar.':'Productos seleccionados, directo del campo y con entrega en La Serena y Coquimbo.'}</p></section>{(!route.cat||route.cat==='huevos')&&<EggWeightGuide/>}<div className="dr-tools"><div><button onClick={()=>setFilters(!filters)}><Filter/>Categorías <ChevronDown/></button><span>{shown.length} producto{shown.length===1?'':'s'}</span></div><div className="dr-tool-actions">{(!route.cat||route.cat==='huevos')&&<label><span className="dr-color-dot" data-color={colorFilter}/>Color <select value={colorFilter} onChange={e=>setColorFilter(e.target.value)} aria-label="Filtrar huevos por color"><option value="all">Todos</option><option value="mixtos">Mixtos</option><option value="blancos">Blancos</option><option value="cafe">Café</option></select></label>}<label><SlidersHorizontal/>Ordenar <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Destacados</option><option value="low">Precio: menor a mayor</option><option value="high">Precio: mayor a menor</option><option value="name">Nombre</option></select></label></div></div>{filters&&<div className="dr-filters"><button onClick={()=>catalog()}>Todos</button>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}</div>}<div className="dr-grid">{shown.map(p=><Card key={p.id} p={p} local={local} open={open} add={add} tiers={store?.xlWelcomeTiers}/>)}</div>{!shown.length&&<div className="dr-empty"><Search/><h2>No encontramos productos</h2><button onClick={()=>{setSearch('');setColorFilter('all');catalog()}}>Ver catálogo completo</button></div>}</main>}
    {route.page==='product'&&<main className="dr-product">{selected?<><button className="dr-back" onClick={()=>catalog(category(selected))}><ArrowLeft/>Volver a {category(selected)}</button><section><div className="dr-product-img"><Pic p={selected} local={local}/>{category(selected)==='Huevos'&&<b className="dr-product-weight">Categoría {eggCaliber(selected).name} · {eggCaliber(selected).weight} por huevo</b>}</div><div className="dr-product-info"><small>{category(selected)==='Huevos'?`Categoría de peso: ${eggCaliber(selected).name}`:category(selected)}</small><h1>{title(selected.title)}</h1><strong>{money(previewPrice(selected,store?.xlWelcomeTiers))}</strong>{previewPrice(selected,store?.xlWelcomeTiers)<Number(selected.price)&&<small>Precio por cantidad</small>}{category(selected)==='Huevos'&&<div className="dr-product-weight-note"><p><b>Peso por huevo: {eggCaliber(selected).weight}</b></p><p>Clasificamos por el peso del huevo con cáscara, no por su apariencia.</p>{['L','XL'].includes(eggCaliber(selected).name)&&<p>Nuestra selección comercial suma 2 g a los extremos de referencia: L de 56 a 63 g y XL de 63 a 70 g. Consulta abajo la clasificación chilena.</p>}{eggCaliber(selected).name==='Jumbo'&&<p>Jumbo es nuestra selección comercial sobre 74 g, dentro de la categoría Especial.</p>}<button onClick={()=>go('/como-comprar',{page:'how'})}>Ver categorías de peso</button></div>}<p>{(category(selected)==='Huevos'?selected.description?.replace(/tamaño/gi,'categoría de peso'):selected.description)||'Producto cuidadosamente seleccionado por Diez Ríos para llevar frescura, sabor y origen a tu mesa.'}</p><ul><li><Leaf/>Selección responsable y de origen</li><li><Truck/>Despacho en La Serena y Coquimbo</li><li><ShieldCheck/>Compra y coordinación segura</li></ul><label>Cantidad</label><Qty n={qty} minus={()=>setQty(Math.max(1,qty-1))} plus={()=>setQty(qty+1)}/><button className="dr-add" disabled={Number(selected.stock)<=0} onClick={()=>add(selected,qty)}><ShoppingBag/>{Number(selected.stock)<=0?'Sin stock':`Agregar al carrito · ${money(previewPrice(selected,store?.xlWelcomeTiers,qty))}`}</button><button className="dr-buy" disabled={Number(selected.stock)<=0} onClick={()=>{add(selected,qty);setCartOpen(false);setCheckout(true)}}>{Number(selected.stock)<=0?'Producto agotado':'Comprar ahora'}</button><aside><Clock3/><span><b>Entrega rápida</b>Compra antes de las 13:00 para recibir el mismo día.</span></aside></div></section><div className="dr-related"><h2>También te puede gustar</h2><div className="dr-grid">{products.filter(p=>p.id!==selected.id).slice(0,4).map(p=><Card key={p.id} p={p} local={local} open={open} add={add} tiers={store?.xlWelcomeTiers}/>)}</div></div></>:<div className="dr-empty"><h2>Producto no encontrado</h2><button onClick={()=>catalog()}>Volver al catálogo</button></div>}</main>}
    {route.page==='how'&&<main><section className="dr-banner dr-big"><small>DIEZ RÍOS</small><h1>Cómo comprar</h1><p>Todo lo que necesitas saber sobre pedidos, entregas y cobertura.</p></section><EggWeightGuide expanded/><section className="dr-info"><small>ENTREGAS SIMPLES Y TRANSPARENTES</small><h2>Costos y condiciones de envío</h2><div><article><Truck/><h3>Despacho a domicilio</h3><p>Lunes a sábado. Compra antes de las 13:00 para recibir el mismo día.</p></article><article><Leaf/><h3>Envío gratis desde {money(free)}</h3><p>Para pedidos menores, el despacho cuesta $1.500.</p></article><article><ShoppingBag/><h3>Sin compra mínima</h3><p>Pide exactamente lo que necesitas.</p></article></div></section><section className="dr-schedule"><div><small>PLANIFICA TU PEDIDO</small><h2>Días y horarios</h2><p>Después de las 13:00 coordinaremos la entrega para el siguiente día hábil.</p></div><div>{['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map(d=><p key={d}><b>{d}</b><span>Hasta 13:00</span><strong>Mismo día</strong></p>)}<p><b>Domingo</b><span>Sin despachos</span><strong>Cerrado</strong></p></div></section><section className="dr-coverage"><div><small>COBERTURA</small><h2>La Serena y Coquimbo</h2><p>Llegamos a ambas comunas. Si tienes dudas sobre tu sector, escríbenos antes de comprar.</p><a href={`https://wa.me/${wa}`} target="_blank" rel="noopener noreferrer"><MessageCircle/>Consultar cobertura</a></div><b>LA SERENA ↕ COQUIMBO</b></section><section className="dr-faq"><small>PREGUNTAS FRECUENTES</small><h2>Resolvemos tus dudas</h2>{[['¿Hasta qué hora puedo pedir para recibir el mismo día?','Hasta las 13:00, de lunes a sábado.'],['¿Realizan entregas los domingos?','No. Los pedidos se coordinan para el lunes.'],['¿Los descuentos se aplican automáticamente?','Las promociones se reflejan en el precio o se confirman al coordinar.'],['¿Qué pasa si no estoy en casa?','Te contactaremos por WhatsApp para coordinar una nueva entrega.'],['¿Despachan fuera de La Serena y Coquimbo?','Consulta pedidos especiales directamente por WhatsApp.']].map((x,i)=><article key={x[0]}><button onClick={()=>setFaq(faq===i?-1:i)}>{x[0]}<ChevronDown/></button>{faq===i&&<p>{x[1]}</p>}</article>)}</section><section className="dr-ready"><h2>¿Listo para pedir?</h2><button onClick={()=>catalog()}>Ver productos <ChevronRight/></button></section></main>}
    {route.page==='story'&&<main><section className="dr-story-hero"><div><small>NUESTRA HISTORIA</small><h1>Una forma más cercana de llevar el campo a tu mesa.</h1><p>Diez Ríos nace del cariño por los alimentos con origen, el trabajo bien hecho y la convicción de que comer mejor también significa saber de dónde viene cada producto.</p></div><img src={`${ASSETS}/story.jpg`} alt="Historia Diez Ríos"/></section><section className="dr-story"><div><small>CAMPO · FAMILIA · ORIGEN</small><h2>Creemos en lo simple y honesto.</h2></div><div><p>Comenzamos acercando huevos de campo a familias de La Serena y Coquimbo. Con el tiempo sumamos productos elegidos bajo el mismo principio: buena procedencia, sabor auténtico y una relación directa.</p><p>Hoy seguimos creciendo sin perder esa cercanía. Seleccionamos cada producto y preparamos cada pedido como nos gustaría recibirlo en nuestra propia casa.</p></div></section><section className="dr-principles">{[['Origen','Conocemos la procedencia de lo que ofrecemos.'],['Confianza','Cuidamos la calidad y hablamos con transparencia.'],['Cercanía','Atendemos personas, no números de pedido.'],['Compromiso','Acompañamos el producto hasta tu mesa.']].map((x,i)=><article key={x[0]}><span>0{i+1}</span><Leaf/><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section><blockquote>“Queremos que cada entrega recuerde que detrás de un buen alimento hay personas, dedicación y una historia que vale la pena cuidar.”<small>Equipo Diez Ríos</small></blockquote><section className="dr-ready"><h2>Conoce nuestros productos</h2><button onClick={()=>catalog()}>Ir al catálogo <ChevronRight/></button></section></main>}
    {footer}
    {cartOpen&&<div className="dr-layer"><button className="dr-overlay" onClick={()=>setCartOpen(false)}/><aside className="dr-cart"><header><div><b>Tu carrito</b><small>{count} {count===1?'producto':'productos'}</small></div><button onClick={()=>setCartOpen(false)}><X/></button></header>{total>0&&<div className="dr-progress"><b>{total>=free?'¡Tienes despacho gratis!':`Te faltan ${money(free-total)} para despacho gratis`}</b><span><i style={{width:`${Math.min(100,total/free*100)}%`}}/></span></div>}<main>{cart.length?cart.map(i=><article key={i.p.id}><Pic p={i.p} local={local}/><div><b>{title(i.p.title)}</b><small>{money(linePrice(i.p.id))} c/u</small><Qty n={i.q} minus={()=>change(i.p.id,-1)} plus={()=>change(i.p.id,1)}/></div><strong>{money(i.q*linePrice(i.p.id))}</strong></article>):<div className="dr-empty"><ShoppingBag/><h2>Tu carrito está vacío</h2>{lastOrder&&<button className="dr-repeat-empty" onClick={repeatLastOrder}><RotateCcw/>Repetir último pedido</button>}<button onClick={()=>{setCartOpen(false);catalog()}}>Ver productos</button></div>}</main>{cart.length>0&&<footer><div><span>Subtotal</span><b>{money(total)}</b></div><small>{store?.xlWelcomeTiers&&!currentQuote?'Descuento por cantidad aplicado automáticamente. ':''}El despacho se confirma según monto y cobertura.</small><button onClick={()=>{setCartOpen(false);setCheckout(true)}}>Finalizar compra <ChevronRight/></button></footer>}</aside></div>}
    {upsell&&<div className="dr-upsell-layer"><section role="dialog" aria-modal="true" aria-labelledby="dr-upsell-title" className="dr-upsell"><div className="dr-upsell-product"><Pic p={upsell} local={local}/><div><small>COMPLETA TU COMPRA</small><b>{title(upsell.title)}</b><span>{unitsFor(upsell)?`${upsell.offerQuantity*unitsFor(upsell)} huevos en total`:`${upsell.offerQuantity} bandejas de la misma variedad`}</span></div></div><h2 id="dr-upsell-title">{upsell.offerQuantity===3?'¡Con tres bandejas ahorras más!':'¡La segunda bandeja cuesta menos!'}</h2><p>Agrega otra por <b>{money(previewPrice(upsell,store?.xlWelcomeTiers,upsell.offerQuantity)-previewPrice(upsell,store?.xlWelcomeTiers,upsell.offerQuantity-1))}</b> y ahorra <b>{money(upsell.offerQuantity*Number(upsell.price)-previewPrice(upsell,store?.xlWelcomeTiers,upsell.offerQuantity))}</b>.</p><p>{upsell.offerQuantity} bandejas por <b>{money(previewPrice(upsell,store?.xlWelcomeTiers,upsell.offerQuantity))}</b>.</p><button autoFocus onClick={()=>{setUpsell(null);add(upsell)}}>Agregar otra bandeja</button><button onClick={()=>setUpsell(null)}>Continuar con mi pedido</button></section></div>}
    {checkout&&<div className="dr-layer"><button className="dr-overlay" onClick={()=>setCheckout(false)}/><section className="dr-checkout"><header><button onClick={()=>setCheckout(false)}><ArrowLeft/>Volver</button><b>DIEZ RÍOS</b><span>Pago contra entrega</span></header><div><form onSubmit={submit}><small>DATOS DE ENTREGA</small><h2>{lastOrder?'Confirma tus datos':'Completa tu pedido'}</h2><p>Te contactaremos por WhatsApp para confirmar.</p>{lastOrder&&<div className="dr-saved-data"><CheckCircle/><span><b>Compra más rápida</b>Tus datos anteriores ya están completados. Revísalos y confirma.</span></div>}{[['Nombre completo','name','text'],['WhatsApp','phone','tel'],['Dirección','address','text']].map(x=><label key={x[1]}>{x[0]}<input type={x[2]} autoComplete={x[1]==='name'?'name':x[1]==='phone'?'tel':'street-address'} value={form[x[1]]} onChange={e=>setForm({...form,[x[1]]:e.target.value})}/></label>)}<label>Comuna<select value={form.city} onChange={e=>setForm({...form,city:e.target.value})}><option>La Serena</option><option>Coquimbo</option></select></label>{formError&&<em>{formError}</em>}<p role="status">{quoteError||(currentQuote?'Precio verificado para tu compra.':'Ingresa tu WhatsApp para verificar el beneficio y el total.')}</p><button disabled={submitting||!currentQuote}>{submitting?'Confirmando…':`Confirmar pedido · ${money(total)}`}</button></form><aside><h3>Resumen</h3>{cart.map(i=><p key={i.p.id}><span>{i.q} × {title(i.p.title)}</span><b>{money(i.q*linePrice(i.p.id))}</b></p>)}<hr/><p><strong>Total</strong><strong>{money(total)}</strong></p></aside></div></section></div>}
    {success&&<div className="dr-success"><section className={recommendations.length?'has-recommendations':''}><div className="dr-success-main"><CheckCircle/><small>PEDIDO RECIBIDO</small><h2>¡Gracias, {form.name.split(' ')[0]}!</h2><p>Recibimos tu pedido #{success.orderId}. Te contactaremos por WhatsApp para confirmar.</p><b>{money(success.total)}</b></div>{recommendations.length>0&&<div className="dr-post-purchase"><small>UNA BUENA COMBINACIÓN</small><h3>¿Quieres llevar algo diferente?</h3><p>Elegimos productos de otras categorías. Tus datos ya están guardados para pedirlos enseguida.</p><div>{recommendations.map(p=><article key={p.id}><Pic p={p} local={local}/><span><small>{category(p)}</small><b>{title(p.title)}</b><strong>{money(p.price)}</strong></span><button onClick={()=>{setSuccess(null);add(p)}}>Agregar</button></article>)}</div></div>}<button className="dr-success-back" onClick={()=>{setSuccess(null);go('',{page:'home'})}}>Seguir viendo la tienda</button></section></div>}
    <a className="dr-wa" href={`https://wa.me/${wa}`} target="_blank" rel="noopener noreferrer" aria-label="Comprar por WhatsApp"><MessageCircle/></a>
    <nav className="dr-bottom-nav" aria-label="Navegación principal"><button className={route.page==='home'?'active':''} onClick={()=>go('',{page:'home'})}><Home/><span>Inicio</span></button><button className={route.page==='catalog'?'active':''} onClick={()=>catalog()}><Search/><span>Productos</span></button><button className={cartOpen?'active':''} onClick={()=>setCartOpen(true)}><ShoppingBag/><span>Carrito</span>{count>0&&<b>{count}</b>}</button><button className={menu?'active':''} onClick={()=>setMenu(true)}><Menu/><span>Más</span></button></nav>
  </div>
}
