import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle, ChevronDown, ChevronRight, Clock3, Filter, Leaf, Menu, MessageCircle, Minus, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Truck, X } from 'lucide-react';
import './tienda.css';

const API = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3001';
const ASSETS = '/store-assets/diez-rios';
const money = n => `$${Math.round(Number(n) || 0).toLocaleString('es-CL')}`;
const norm = s => String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const slugify = s => norm(s).replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const title = s => String(s || '').replace(/^[^\p{L}\p{N}]+/u, '').trim();
const request = async (path, options) => { const r = await fetch(`${API}${path}`, options); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'No pudimos completar la solicitud'); return d; };
const localImages = { 1:'huevos-bandeja.png',2:'huevos-bandeja.png',3:'huevos-bandeja.png',4:'huevos-bandeja.png',5:'huevos-bandeja-xl.png',6:'caja-m.png',7:'caja-l.png',8:'caja-xl.png',9:'caja-jumbo.png',10:'queso-vaca.png',11:'queso-cabra.png',12:'aceitunas-verdes.jpg',13:'aceitunas-negras.jpg',14:'aceitunas-moradas.jpg',15:'promo-60-xl.jpg',16:'pack-campo.png',18:'promo-m.jpg',21:'aceitunas-rajadas.jpg' };
const category = p => { const s = norm(`${p?.category} ${p?.title}`); return s.includes('queso')?'Quesos':s.includes('aceituna')?'Aceitunas':(s.includes('promo')||s.includes('pack'))?'Promociones':'Huevos'; };
const fallback = { Huevos:'huevos-bandeja.png',Quesos:'queso-vaca.png',Aceitunas:'aceitunas-verdes.jpg',Promociones:'promo-60-xl.jpg' };
const unitsFor = p => { const match=String(p?.title||'').match(/(\d+)\s*(?:huevos|unidades|un\b)/i); return match?Number(match[1]):null; };
const eggTone = p => { const name=norm(p?.title); return name.includes('blanco')?'Huevos blancos':name.includes('cafe')?'Huevos cafés':'Huevos mixtos'; };
const eggImage = p => {
  const name=norm(p?.title), units=unitsFor(p), bulk=Number(units)>=100;
  const tone=name.includes('blanco')?'blancos':name.includes('cafe')?'cafe':'mixtos';
  if(bulk)return`caja-cerrada-huevos-${tone}-v4.jpg`;
  if(units===20)return`huevos-${tone}-20-hogar-v4.jpg`;
  if(tone==='cafe')return'huevos-cafe-30-hogar-v4.jpg';
  return`huevos-${tone}-hogar-v3.jpg`;
};
const imageFor = (p, local) => local ? `${ASSETS}/${category(p)==='Huevos'?eggImage(p):(localImages[p.id] || fallback[category(p)])}` : p.image_url;

function routeFrom(base) { const tail = base && location.pathname.startsWith(base) ? location.pathname.slice(base.length) : location.pathname; const a = tail.split('/').filter(Boolean); if (a[0]==='productos'&&a[1]) return {page:'product',id:Number(a[1].split('-')[0])}; if(a[0]==='productos')return{page:'catalog'}; if(a[0]==='colecciones')return{page:'catalog',cat:a[1]}; if(a[0]==='como-comprar')return{page:'how'}; if(a[0]==='nuestra-historia')return{page:'story'}; return{page:'home'}; }
function Qty({n,minus,plus}){return <div className="dr-qty"><button onClick={minus}><Minus/></button><b>{n}</b><button onClick={plus}>+</button></div>}
function Pic({p,local,className=''}){const [bad,setBad]=useState(false);return bad?<div className={`dr-fallback ${className}`}><Leaf/></div>:<img className={className} src={imageFor(p,local)} alt={title(p.title)} loading="lazy" onError={()=>setBad(true)}/>}
function Card({p,local,open,add}){const eggs=category(p)==='Huevos',units=eggs&&unitsFor(p);return <article className="dr-card"><button className="dr-card-pic" onClick={()=>open(p)}><Pic p={p} local={local}/>{eggs&&<i>{eggTone(p)}</i>}{units&&<b className="dr-card-units">{units} UN.</b>}{Number(p.stock)===0&&<span>Agotado</span>}</button><small>{eggs?eggTone(p):category(p)}</small><button className="dr-card-title" onClick={()=>open(p)}>{title(p.title)}</button><strong>{money(p.price)}</strong><button className="dr-card-add" disabled={Number(p.stock)===0} onClick={()=>add(p)}><ShoppingBag/>Agregar al carrito</button></article>}

export default function Tienda({slug}){
  const local=slug.startsWith('diez-rios'), custom=['diezrios.com','www.diezrios.com'].includes(location.hostname), base=custom?'':`/tienda/${slug}`;
  const shellRef=useRef(null);
  const [route,setRoute]=useState(()=>routeFrom(base)),[store,setStore]=useState(null),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[menu,setMenu]=useState(false),[searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(''),[sort,setSort]=useState('featured'),[filters,setFilters]=useState(false),[faq,setFaq]=useState(-1),[qty,setQty]=useState(1),[checkout,setCheckout]=useState(false),[success,setSuccess]=useState(null),[submitting,setSubmitting]=useState(false),[form,setForm]=useState({name:'',phone:'',address:'',city:'La Serena'}),[formError,setFormError]=useState('');
  useEffect(()=>{const pop=()=>setRoute(routeFrom(base));addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[base]);
  useEffect(()=>{Promise.all([request(`/store/${slug}/info`),request(`/store/${slug}/products`)]).then(([s,p])=>{setStore(s);setProducts((p.products||[]).filter(x=>x.active!==false&&x.is_business!==true))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[slug]);
  const go=useCallback((path,r)=>{history.pushState({},'',`${base}${path}`||'/');setRoute(r);setMenu(false);setSearchOpen(false);setCheckout(false);shellRef.current?.scrollTo({top:0,behavior:'smooth'})},[base]);
  const cats=useMemo(()=>['Huevos','Quesos','Aceitunas','Promociones'].filter(c=>products.some(p=>category(p)===c)),[products]);
  const shown=useMemo(()=>{let a=[...products];if(route.cat)a=a.filter(p=>slugify(category(p))===route.cat);if(search)a=a.filter(p=>norm(p.title).includes(norm(search)));if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='name')a.sort((x,y)=>title(x.title).localeCompare(title(y.title),'es'));return a},[products,route.cat,search,sort]);
  const selected=products.find(p=>p.id===route.id),free=Number(store?.freeShipping??10000),wa=String(store?.whatsappPhone||'56939490738').replace(/\D/g,''),count=cart.reduce((s,i)=>s+i.q,0),total=cart.reduce((s,i)=>s+i.q*Number(i.p.price),0);
  const add=useCallback((p,n=1)=>{setCart(a=>{const e=a.find(i=>i.p.id===p.id);return e?a.map(i=>i.p.id===p.id?{...i,q:i.q+n}:i):[...a,{p,q:n}]});setCartOpen(true)},[]);
  const change=(id,d)=>setCart(a=>a.map(i=>i.p.id===id?{...i,q:i.q+d}:i).filter(i=>i.q>0));
  const catalog=c=>c?go(`/colecciones/${slugify(c)}`,{page:'catalog',cat:slugify(c)}):go('/productos',{page:'catalog'});
  const open=p=>go(`/productos/${p.id}-${slugify(title(p.title))}`,{page:'product',id:p.id});
  const submit=async e=>{e.preventDefault();if(!form.name.trim()||form.phone.replace(/\D/g,'').length<8||!form.address.trim()){setFormError('Completa nombre, WhatsApp y dirección.');return}setSubmitting(true);try{const d=await request(`/store/${slug}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,items:cart.map(i=>({productId:i.p.id,quantity:i.q}))})});setSuccess(d);setCart([]);setCheckout(false)}catch(x){setFormError(x.message)}finally{setSubmitting(false)}};
  if(loading)return <div className="dr-state"><i/><p>Preparando productos frescos…</p></div>;if(error)return <div className="dr-state"><Leaf/><h1>Tienda temporalmente no disponible</h1><p>{error}</p><button onClick={()=>location.reload()}>Intentar nuevamente</button></div>;
  const header=<><div className="dr-ann"><Truck/>Delivery gratis por compras sobre {money(free)}</div><header className="dr-header"><button className="dr-menu-trigger" onClick={()=>setMenu(true)}><Menu/></button><button className="dr-logo" onClick={()=>go('',{page:'home'})}><b>DIEZ RÍOS</b><span>CAMPO · FAMILIA · ORIGEN</span></button><nav><div><button>Productos <ChevronDown/></button><aside>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}<button onClick={()=>catalog()}>Ver todos</button></aside></div><button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></nav><section><button onClick={()=>setSearchOpen(!searchOpen)}><Search/></button><button className="dr-bag" onClick={()=>setCartOpen(true)}><ShoppingBag/>{count>0&&<i>{count}</i>}</button></section></header>{searchOpen&&<div className="dr-search"><Search/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos…"/><button onClick={()=>setSearch('')}><X/></button></div>}{menu&&<div className="dr-mobile"><div><b>MENÚ</b><button onClick={()=>setMenu(false)}><X/></button></div><button onClick={()=>go('',{page:'home'})}>Inicio</button><button onClick={()=>catalog()}>Todos los productos</button>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}<button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></div>}</>;
  const footer=<footer className="dr-footer"><section><div><small>COMPRA DIRECTO AL CAMPO</small><h2>Productos honestos,<br/>directo a tu mesa.</h2></div><a href={`https://wa.me/${wa}`} target="_blank"><MessageCircle/>Comprar por WhatsApp</a></section><div className="dr-footer-grid"><div><b>DIEZ RÍOS</b><p>Alimentos de origen, seleccionados con dedicación y entregados directamente en tu hogar.</p></div><div><strong>Comprar</strong>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}</div><div><strong>Información</strong><button onClick={()=>go('/como-comprar',{page:'how'})}>Cómo comprar</button><button onClick={()=>go('/nuestra-historia',{page:'story'})}>Nuestra historia</button></div><div><strong>Despachos</strong><p>La Serena y Coquimbo<br/>Lunes a sábado<br/>Pedidos antes de las 11:00</p></div></div><small>© {new Date().getFullYear()} Diez Ríos · Compra segura</small></footer>;
  return <div ref={shellRef} className={`dr-shell${cartOpen||menu||checkout?' dr-scroll-locked':''}`}>{header}
    {route.page==='home'&&<main><section className="dr-hero"><div className="dr-hero-copy"><div className="dr-pills"><span>5% OFF POR 2 BANDEJAS</span><span>DESPACHO GRATIS SOBRE {money(free)}</span></div><small>ALIMENTOS CON ORIGEN</small><h1>Del campo<br/>a tu mesa.</h1><p>Huevos de gallinas libres, quesos artesanales y aceitunas seleccionadas. Productos frescos, sin intermediarios y con entrega directa en La Serena y Coquimbo.</p><ul><li><CheckCircle/>Producción y selección responsable</li><li><CheckCircle/>Entrega directa, sin intermediarios</li><li><CheckCircle/>Atención cercana por WhatsApp</li></ul><button onClick={()=>catalog()}>Ver productos <ChevronRight/></button><em>★★★★★ &nbsp; Preferidos por familias de la región</em></div><div className="dr-hero-img"><img src={`${ASSETS}/hero.png`} alt="Productos Diez Ríos"/><span><Leaf/><b>100%</b>origen local</span></div></section>
    <section className="dr-values"><small>NUESTRA FORMA DE HACER LAS COSAS</small><h2>Dedicación en cada producto</h2><p>Creemos en los alimentos simples, honestos y bien hechos. Por eso cuidamos cada paso, desde el origen hasta tu puerta.</p><div><article><b>100%</b><strong>Gallinas libres</strong><span>Huevos de campo seleccionados con cuidado.</span></article><article><b>0</b><strong>Intermediarios</strong><span>Del productor directamente a tu hogar.</span></article><article><b>52</b><strong>Semanas al año</strong><span>Una relación constante con nuestros clientes.</span></article></div></section>
    <section className="dr-featured"><div className="dr-heading"><div><small>NUESTROS PRODUCTOS</small><h2>Delicias del campo</h2></div><button onClick={()=>catalog()}>Ver todo <ChevronRight/></button></div><div className="dr-categories">{[['Huevos','huevos-bandeja.png','Frescos, de gallinas libres'],['Quesos','queso-cabra.png','Artesanales y llenos de sabor'],['Aceitunas','aceitunas-verdes.jpg','Seleccionadas en su mejor punto']].map(([c,img,t])=><button key={c} onClick={()=>catalog(c)}><img src={`${ASSETS}/${img}`} alt={c}/><span><small>{t}</small><b>{c}</b><em>Comprar ahora →</em></span></button>)}</div></section>
    <section className="dr-how-preview"><small>ASÍ DE SIMPLE</small><h2>Cómo funciona</h2><div>{[['01','Elige','Agrega tus productos favoritos.'],['02','Confirma','Ingresa tus datos y dirección.'],['03','Coordinamos','Te contactamos por WhatsApp.'],['04','Recibe','Llevamos el campo a tu puerta.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><button onClick={()=>go('/como-comprar',{page:'how'})}>Ver entregas y condiciones <ChevronRight/></button></section></main>}
    {route.page==='catalog'&&<main className="dr-catalog"><section className="dr-banner"><small>CATÁLOGO DIEZ RÍOS</small><h1>{route.cat?cats.find(c=>slugify(c)===route.cat):'Todos los productos'}</h1><p>Productos seleccionados, directo del campo y con entrega en La Serena y Coquimbo.</p></section><div className="dr-tools"><div><button onClick={()=>setFilters(!filters)}><Filter/>Categorías <ChevronDown/></button><span>{shown.length} productos</span></div><label><SlidersHorizontal/>Ordenar <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Destacados</option><option value="low">Precio: menor a mayor</option><option value="high">Precio: mayor a menor</option><option value="name">Nombre</option></select></label></div>{filters&&<div className="dr-filters"><button onClick={()=>catalog()}>Todos</button>{cats.map(c=><button key={c} onClick={()=>catalog(c)}>{c}</button>)}</div>}<div className="dr-grid">{shown.map(p=><Card key={p.id} p={p} local={local} open={open} add={add}/>)}</div>{!shown.length&&<div className="dr-empty"><Search/><h2>No encontramos productos</h2><button onClick={()=>{setSearch('');catalog()}}>Ver catálogo completo</button></div>}</main>}
    {route.page==='product'&&<main className="dr-product">{selected?<><button className="dr-back" onClick={()=>catalog(category(selected))}><ArrowLeft/>Volver a {category(selected)}</button><section><div className="dr-product-img"><Pic p={selected} local={local}/></div><div className="dr-product-info"><small>{category(selected)}</small><h1>{title(selected.title)}</h1><strong>{money(selected.price)}</strong><p>{selected.description||'Producto cuidadosamente seleccionado por Diez Ríos para llevar frescura, sabor y origen a tu mesa.'}</p><ul><li><Leaf/>Selección responsable y de origen</li><li><Truck/>Despacho en La Serena y Coquimbo</li><li><ShieldCheck/>Compra y coordinación segura</li></ul><label>Cantidad</label><Qty n={qty} minus={()=>setQty(Math.max(1,qty-1))} plus={()=>setQty(qty+1)}/><button className="dr-add" onClick={()=>add(selected,qty)}><ShoppingBag/>Agregar al carrito · {money(selected.price*qty)}</button><button className="dr-buy" onClick={()=>{add(selected,qty);setCartOpen(false);setCheckout(true)}}>Comprar ahora</button><aside><Clock3/><span><b>Entrega rápida</b>Compra antes de las 11:00 para recibir el mismo día.</span></aside></div></section><div className="dr-related"><h2>También te puede gustar</h2><div className="dr-grid">{products.filter(p=>p.id!==selected.id).slice(0,4).map(p=><Card key={p.id} p={p} local={local} open={open} add={add}/>)}</div></div></>:<div className="dr-empty"><h2>Producto no encontrado</h2><button onClick={()=>catalog()}>Volver al catálogo</button></div>}</main>}
    {route.page==='how'&&<main><section className="dr-banner dr-big"><small>DIEZ RÍOS</small><h1>Cómo comprar</h1><p>Todo lo que necesitas saber sobre pedidos, entregas y cobertura.</p></section><section className="dr-info"><small>ENTREGAS SIMPLES Y TRANSPARENTES</small><h2>Costos y condiciones de envío</h2><div><article><Truck/><h3>Despacho a domicilio</h3><p>Lunes a sábado. Compra antes de las 11:00 para recibir el mismo día.</p></article><article><Leaf/><h3>Envío gratis desde {money(free)}</h3><p>Para pedidos menores, el despacho cuesta $1.500.</p></article><article><ShoppingBag/><h3>Sin compra mínima</h3><p>Pide exactamente lo que necesitas.</p></article></div></section><section className="dr-schedule"><div><small>PLANIFICA TU PEDIDO</small><h2>Días y horarios</h2><p>Después de las 11:00 coordinaremos la entrega para el siguiente día hábil.</p></div><div>{['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map(d=><p key={d}><b>{d}</b><span>Hasta 11:00</span><strong>Mismo día</strong></p>)}<p><b>Domingo</b><span>Sin despachos</span><strong>Cerrado</strong></p></div></section><section className="dr-coverage"><div><small>COBERTURA</small><h2>La Serena y Coquimbo</h2><p>Llegamos a ambas comunas. Si tienes dudas sobre tu sector, escríbenos antes de comprar.</p><a href={`https://wa.me/${wa}`} target="_blank"><MessageCircle/>Consultar cobertura</a></div><b>LA SERENA ↕ COQUIMBO</b></section><section className="dr-faq"><small>PREGUNTAS FRECUENTES</small><h2>Resolvemos tus dudas</h2>{[['¿Hasta qué hora puedo pedir para recibir el mismo día?','Hasta las 11:00, de lunes a sábado.'],['¿Realizan entregas los domingos?','No. Los pedidos se coordinan para el lunes.'],['¿Los descuentos se aplican automáticamente?','Las promociones se reflejan en el precio o se confirman al coordinar.'],['¿Qué pasa si no estoy en casa?','Te contactaremos por WhatsApp para coordinar una nueva entrega.'],['¿Despachan fuera de La Serena y Coquimbo?','Consulta pedidos especiales directamente por WhatsApp.']].map((x,i)=><article key={x[0]}><button onClick={()=>setFaq(faq===i?-1:i)}>{x[0]}<ChevronDown/></button>{faq===i&&<p>{x[1]}</p>}</article>)}</section><section className="dr-ready"><h2>¿Listo para pedir?</h2><button onClick={()=>catalog()}>Ver productos <ChevronRight/></button></section></main>}
    {route.page==='story'&&<main><section className="dr-story-hero"><div><small>NUESTRA HISTORIA</small><h1>Una forma más cercana de llevar el campo a tu mesa.</h1><p>Diez Ríos nace del cariño por los alimentos con origen, el trabajo bien hecho y la convicción de que comer mejor también significa saber de dónde viene cada producto.</p></div><img src={`${ASSETS}/story.jpg`} alt="Historia Diez Ríos"/></section><section className="dr-story"><div><small>CAMPO · FAMILIA · ORIGEN</small><h2>Creemos en lo simple y honesto.</h2></div><div><p>Comenzamos acercando huevos de campo a familias de La Serena y Coquimbo. Con el tiempo sumamos productos elegidos bajo el mismo principio: buena procedencia, sabor auténtico y una relación directa.</p><p>Hoy seguimos creciendo sin perder esa cercanía. Seleccionamos cada producto y preparamos cada pedido como nos gustaría recibirlo en nuestra propia casa.</p></div></section><section className="dr-principles">{[['Origen','Conocemos la procedencia de lo que ofrecemos.'],['Confianza','Cuidamos la calidad y hablamos con transparencia.'],['Cercanía','Atendemos personas, no números de pedido.'],['Compromiso','Acompañamos el producto hasta tu mesa.']].map((x,i)=><article key={x[0]}><span>0{i+1}</span><Leaf/><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section><blockquote>“Queremos que cada entrega recuerde que detrás de un buen alimento hay personas, dedicación y una historia que vale la pena cuidar.”<small>Equipo Diez Ríos</small></blockquote><section className="dr-ready"><h2>Conoce nuestros productos</h2><button onClick={()=>catalog()}>Ir al catálogo <ChevronRight/></button></section></main>}
    {footer}
    {cartOpen&&<div className="dr-layer"><button className="dr-overlay" onClick={()=>setCartOpen(false)}/><aside className="dr-cart"><header><div><b>Tu carrito</b><small>{count} productos</small></div><button onClick={()=>setCartOpen(false)}><X/></button></header>{total>0&&<div className="dr-progress"><b>{total>=free?'¡Tienes despacho gratis!':`Te faltan ${money(free-total)} para despacho gratis`}</b><span><i style={{width:`${Math.min(100,total/free*100)}%`}}/></span></div>}<main>{cart.length?cart.map(i=><article key={i.p.id}><Pic p={i.p} local={local}/><div><b>{title(i.p.title)}</b><small>{money(i.p.price)} c/u</small><Qty n={i.q} minus={()=>change(i.p.id,-1)} plus={()=>change(i.p.id,1)}/></div><strong>{money(i.q*i.p.price)}</strong></article>):<div className="dr-empty"><ShoppingBag/><h2>Tu carrito está vacío</h2><button onClick={()=>{setCartOpen(false);catalog()}}>Ver productos</button></div>}</main>{cart.length>0&&<footer><div><span>Subtotal</span><b>{money(total)}</b></div><small>El despacho se confirma según monto y cobertura.</small><button onClick={()=>{setCartOpen(false);setCheckout(true)}}>Finalizar compra <ChevronRight/></button></footer>}</aside></div>}
    {checkout&&<div className="dr-layer"><button className="dr-overlay" onClick={()=>setCheckout(false)}/><section className="dr-checkout"><header><button onClick={()=>setCheckout(false)}><ArrowLeft/>Volver</button><b>DIEZ RÍOS</b><span>Pago contra entrega</span></header><div><form onSubmit={submit}><small>DATOS DE ENTREGA</small><h2>Completa tu pedido</h2><p>Te contactaremos por WhatsApp para confirmar.</p>{[['Nombre completo','name','text'],['WhatsApp','phone','tel'],['Dirección','address','text']].map(x=><label key={x[1]}>{x[0]}<input type={x[2]} value={form[x[1]]} onChange={e=>setForm({...form,[x[1]]:e.target.value})}/></label>)}<label>Comuna<select value={form.city} onChange={e=>setForm({...form,city:e.target.value})}><option>La Serena</option><option>Coquimbo</option></select></label>{formError&&<em>{formError}</em>}<button disabled={submitting}>{submitting?'Confirmando…':`Confirmar pedido · ${money(total)}`}</button></form><aside><h3>Resumen</h3>{cart.map(i=><p key={i.p.id}><span>{i.q} × {title(i.p.title)}</span><b>{money(i.q*i.p.price)}</b></p>)}<hr/><p><strong>Total</strong><strong>{money(total)}</strong></p></aside></div></section></div>}
    {success&&<div className="dr-success"><section><CheckCircle/><small>PEDIDO RECIBIDO</small><h2>¡Gracias, {form.name.split(' ')[0]}!</h2><p>Recibimos tu pedido #{success.orderId}. Te contactaremos por WhatsApp para confirmar.</p><b>{money(success.total)}</b><button onClick={()=>{setSuccess(null);go('',{page:'home'})}}>Volver a la tienda</button></section></div>}
    <a className="dr-wa" href={`https://wa.me/${wa}`} target="_blank"><MessageCircle/></a>
  </div>
}
