// theme.js — Color palettes for dark and light modes
import { createContext, useContext } from 'react';

export const DARK = {
  bgApp:         '#111b21',
  bgPanel:       '#202c33',
  bgCard:        '#232f37',
  bgSub:         '#1a2428',
  bgInput:       '#111b21',
  bgHover:       '#2a3942',
  bgAccent:      '#0d2e25',
  bgAccent2:     '#1a2030',
  border:        '#2a3942',
  borderStrong:  '#374045',
  borderAccent:  '#00a884',
  textPrimary:   '#e9edef',
  textSecondary: '#8696a0',
  textMuted:     '#556169',
  green:         '#00a884',
  greenLight:    '#00c853',
  greenTint:     '#0d2e25',
  red:           '#e57373',
  yellow:        '#f0b429',
  purple:        '#b8a9ff',
  // ── Tokens semánticos (globales, mismos valores en claro/oscuro) ──
  success:       '#22c55e',
  successSoft:   '#4ade80',
  successStrong: '#16a34a',
  danger:        '#ef4444',
  dangerSoft:    '#f87171',
  warning:       '#fb923c',
  amber:         '#fbbf24',
  amberStrong:   '#f59e0b',
  info:          '#38bdf8',
  infoSoft:      '#4db6e8',
  teal:          '#2dd4bf',
  tealSoft:      '#4db6ac',
  indigo:        '#6366f1',
  pink:          '#e879f9',
  purpleSoft:    '#a78bfa',
  purpleSofter:  '#c4b5fd',
  // ── Escala de espaciado y radios (globales) ──
  radiusSm:      '6px',
  radiusMd:      '8px',
  radiusLg:      '12px',
  radiusPill:    '999px',
  navBg:         '#202c33',
};

export const LIGHT = {
  bgApp:         '#f0f2f5',
  bgPanel:       '#ffffff',
  bgCard:        '#f7f8fa',
  bgSub:         '#f7f8fa',
  bgInput:       '#f5f6f7',
  bgHover:       '#e8eaed',
  bgAccent:      '#d9fdd3',
  bgAccent2:     '#eef1f6',
  border:        '#e9edef',
  borderStrong:  '#d1d7db',
  borderAccent:  '#00a884',
  textPrimary:   '#111b21',
  textSecondary: '#54656f',
  textMuted:     '#8696a0',
  green:         '#00a884',
  greenLight:    '#00c853',
  greenTint:     '#d9fdd3',
  red:           '#c0392b',
  yellow:        '#e08b00',
  purple:        '#6c3dd8',
  // ── Tokens semánticos (globales, mismos valores en claro/oscuro) ──
  success:       '#22c55e',
  successSoft:   '#4ade80',
  successStrong: '#16a34a',
  danger:        '#ef4444',
  dangerSoft:    '#f87171',
  warning:       '#fb923c',
  amber:         '#fbbf24',
  amberStrong:   '#f59e0b',
  info:          '#38bdf8',
  infoSoft:      '#4db6e8',
  teal:          '#2dd4bf',
  tealSoft:      '#4db6ac',
  indigo:        '#6366f1',
  pink:          '#e879f9',
  purpleSoft:    '#a78bfa',
  purpleSofter:  '#c4b5fd',
  // ── Escala de espaciado y radios (globales) ──
  radiusSm:      '6px',
  radiusMd:      '8px',
  radiusLg:      '12px',
  radiusPill:    '999px',
  navBg:         '#ffffff',
};

export const ThemeCtx = createContext({ colors: DARK, isDark: true, toggle: () => {} });
export const useTheme = () => useContext(ThemeCtx);
